# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: bionic
sudo: true
addons:
  apt:
    packages:
      - python3-venv
      - python3-pip
      - python3-setuptools

language: R
cache: packages


install:
  - python3 -m pip -q install --upgrade pip
  - python3 -m pip -q install tensorflow
