# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: true

language: r

addons:
  apt:
    packages:
      - python3-pip


before_install:
  - python3 -m pip -q install --upgrade pip setuptools
  - python3 -m pip -q install tensorflow


# suppress log size
git:
  quiet: true
  depth: 3
